version: '3.8'
services:
  user-app:
    image: 'user-app'
    build:
      context: .
    container_name: user-app
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres_db:5432/user
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres123
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres_db:5432/user
      - SPRING_FLYWAY_USER=postgres
      - SPRING_FLYWAY_PASSWORD=postgres123
      - SPRING_FLYWAY_LOCATIONS=classpath:db/migration
    ports:
      - "8080:8080"
  postgres_db:
    image: postgres:latest
    container_name: UserPostgresContainer
    restart: unless-stopped
    environment:
      - POSTGRES_DB=user
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
        - '5432:5432'
    volumes:
        - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local